# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_auto_20171105_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Biography',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='department',
            new_name='biography',
        ),
    ]
