# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_auto_20171105_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='biography',
            field=models.CharField(max_length=300),
        ),
    ]
