# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0021_auto_20171108_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='biography',
            field=models.TextField(blank=True, default='Details', max_length=500),
        ),
    ]
