# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0022_auto_20171108_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biography',
            new_name='UserBio',
        ),
    ]
