# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0023_auto_20171109_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBio',
            new_name='Biography',
        ),
    ]
