# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20171021_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='value',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='product_type',
        ),
    ]
