# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20171022_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='url',
        ),
    ]
