# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20171022_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
