# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20171022_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default='Img URL', max_length=200),
        ),
    ]
