# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_product_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
