# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20171028_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(default=' ', max_length=200, upload_to=''),
        ),
    ]
