# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20171028_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
