# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
