# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_auto_20171028_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/default.png', null=True, upload_to='product_images'),
        ),
    ]
