# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_auto_20171028_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
