# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default.png', null=True, upload_to='product_images'),
        ),
    ]
